// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_and_trace_transaction_internal`

/// Formats and traces a transaction, returning the result as a JSON string
///
/// This is the main entry point for Flutter/Dart via flutter_rust_bridge.
/// All errors are converted to JSON error responses for graceful handling on the client side.
///
/// # Arguments
///
/// * `chain_id` - The chain ID
/// * `from` - Sender address as hex string
/// * `from_nonce` - Sender's nonce
/// * `to` - Recipient address as hex string
/// * `data` - Transaction data as hex string
/// * `gas_limit` - Gas limit
/// * `gas_price` - Gas price in wei
/// * `gas_priority_fee` - Priority fee in wei
/// * `latest_block_env` - Block environment as JSON string
/// * `prestate_tracer_result` - Prestate as JSON string
/// * `is_op_stack` - If true, use Optimism tracer; if false, use standard Ethereum tracer
///
/// # Returns
///
/// JSON string containing either:
/// - Success: The trace result
/// - Error: An error object with details
String formatAndTraceTransaction(
        {required BigInt chainId,
        required String from,
        required BigInt fromNonce,
        required String to,
        required String data,
        required BigInt gasLimit,
        required BigInt gasPrice,
        required BigInt gasPriorityFee,
        required String latestBlockEnv,
        required String prestateTracerResult,
        required bool isOpStack}) =>
    RustLib.instance.api.crateApiTracerFormatAndTraceTransaction(
        chainId: chainId,
        from: from,
        fromNonce: fromNonce,
        to: to,
        data: data,
        gasLimit: gasLimit,
        gasPrice: gasPrice,
        gasPriorityFee: gasPriorityFee,
        latestBlockEnv: latestBlockEnv,
        prestateTracerResult: prestateTracerResult,
        isOpStack: isOpStack);
